### ISSUE TITLE
SpikeHunter error - cannot import name 'esmfold_structure_module_only_8M' from 'esm.pretrained'

### ISSUE THREAD

**Issue by pvevseev** [nlm-irp-jianglab/SpikeHunter#2]
Hi all,

when I run the python SpikeHunter.py -c predict.yaml -r trained_model/model_best.pth, I got an error 'ImportError: cannot import name 'esmfold_structure_module_only_8M' from 'esm.pretrained'

Here is the error message:

python SpikeHunter.py -c predict.yaml -r trained_model/model_best.pth
Using cache found in /home/peter/Downloads/SpikeHunter/data/facebookresearch_esm_main
Traceback (most recent call last):
  File "SpikeHunter.py", line 76, in <module>
    main(config)
  File "SpikeHunter.py", line 20, in main
    transforms = config.init_obj('transformer', module_tsf)
  File "/home/peter/Downloads/SpikeHunter/parse_config.py", line 94, in init_obj
    return getattr(module, module_name)(*args, **module_args)
  File "/home/peter/Downloads/SpikeHunter/data_loader/augmentation.py", line 19, in __init__
    model, alphabet = torch.hub.load("facebookresearch/esm:main", "esm2_t33_650M_UR50D")
  File "/home/peter/conda/envs/SpikeHunter/lib/python3.8/site-packages/torch/hub.py", line 542, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/home/peter/conda/envs/SpikeHunter/lib/python3.8/site-packages/torch/hub.py", line 569, in _load_local
    hub_module = _import_module(MODULE_HUBCONF, hubconf_path)
  File "/home/peter/conda/envs/SpikeHunter/lib/python3.8/site-packages/torch/hub.py", line 90, in _import_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/peter/Downloads/SpikeHunter/data/facebookresearch_esm_main/hubconf.py", line 8, in <module>
    from esm.pretrained import (
ImportError: cannot import name 'esmfold_structure_module_only_8M' from 'esm.pretrained' (/home/peter/conda/envs/SpikeHunter/lib/python3.8/site-packages/esm/pretrained.py)

Any suggestions how to fix it?

Thanks, Peter

**Comment by michoug** [comment]
Hi,

First I was not involved in this package and I'm not an expert on this topic.
Apparently, the issue is due to the `esm` package that cannot be in use when the command `model, alphabet = torch.hub.load("facebookresearch/esm:main", "esm2_t33_650M_UR50D")` is run in the `data_loader/augmentation.py` script.
As this is used to download some data, which should already be there if you ran 

```
export esm_folder=<your path for downloading ESM models>
python setup.py ${esm_folder}
```

you can try to replace in the `data_loader/augmentation.py` script the command (line 20)

`model, alphabet = torch.hub.load("facebookresearch/esm:main", "esm2_t33_650M_UR50D")`

by 

`model, alphabet = esm.pretrained.esm2_t33_650M_UR50D()`

A simple script that I used to check this is:

```
import esm
import os, torch

model, alphabet = torch.hub.load("facebookresearch/esm:main", "esm2_t33_650M_UR50D")
self.batch_converter = alphabet.get_batch_converter()
```

which fails with the same error but this 

```
import os, torch

model, alphabet = torch.hub.load("facebookresearch/esm:main", "esm2_t33_650M_UR50D")
self.batch_converter = alphabet.get_batch_converter()
```

or this

```
import esm
import os, torch

model, alphabet = esm.pretrained.esm2_t33_650M_UR50D()
self.batch_converter = alphabet.get_batch_converter()
```

works

Best
Greg

**Comment by leannmlindsey** [comment]
Thank you for your suggestion @michoug. We have incorporated this change in the the main branch.
